### PR TITLE
Fix calendar drag

### PR DESCRIPTION
**Pull request by smacz42**
Fixes https://github.com/kanboard/plugin-calendar/issues/11

### CODE REVIEW

**Comment by smacz42** [comment]
Bump

**Comment by smacz42** [comment]
Bump @fguillot

**Comment by Grekkor** [comment]
@smacz42 I have implemented the changes you proposed and now I can effectively move all tasks but they are duplicated and the start and end date are not correct. It has to do with the fact that the task considers the creation date and not the start date. If no start date is set then the task exists twice, if it is set then even when dragging it around the task due date is updated but the the starting date is not considered.

**Comment by Grekkor** [comment]
I was able to properly fix this issue. I will create a pull request for it soon.
The plugin should however, be rewritten as it very messy compared to other plugins.

**Comment by smacz42** [comment]
> I was able to properly fix this issue. I will create a pull request for it soon.
> The plugin should however, be rewritten as it very messy compared to other plugins.

I have not seen a PR on this yet. What type of changes did you have to make to fix the issue?

**Comment by smacz42** [comment]
@Grekkor bump^

FWIW, I wouldn't mind just writing the changes into my PR if you give me a snippet of what needs to be changed.

**Comment by mer30hamid** [comment]
> Fixes #11

I checked your changes and examined it, **It also Fixes #22** !! 
Thank you !

Edit: I checked and examined it more, It shows tasks with no "start date" and "due date", I think its a bug and problem with Persian language.

**Comment by mer30hamid** [comment]
> > Fixes #11
> 
> I checked your changes and examined it, **It also Fixes #22** !!
> Thank you !
> 
> Edit: I checked and examined it more, It shows tasks with no "start date" and "due date", I think its a bug and problem with Persian language.

As I said here: https://github.com/kanboard/plugin-calendar/issues/22#issuecomment-533231310
Edited "locale-all.js" and it fixed, but is there any way to fix it without touching the [fullcalendar](https://fullcalendar.io/) files?

**Comment by smacz42** [comment]
> Edit: I checked and examined it more, It shows tasks with no "start date" and "due date", I think its a bug and problem with Persian language.

Can you describe that a little more? And does this happen with english too?

**Comment by mer30hamid** [comment]
> > Edit: I checked and examined it more, It shows tasks with no "start date" and "due date", I think its a bug and problem with Persian language.
> 
> Can you describe that a little more? And does this happen with english too?

Sorry for my bad English, No, this happens just for languages that have this weird number conversion (As I said here: https://github.com/kanboard/plugin-calendar/issues/22#issuecomment-533231310)

**Comment by smacz42** [comment]
I see in #22: [It seems that this problem is fixed in "Kanboard 1.2.13", perhaps this was an issue about the Kanboard!](https://github.com/kanboard/plugin-calendar/issues/22#issuecomment-567602103) So that seems to be fixed.

I have not seen any PR from @Grekkor with any fixes. This PR should fix the immediate problem, and the any residual issues can be addressed later?

**Comment by fguillot** [comment]
This plugin is now archived. Unfortunately, I do not have the time to maintain or review pull-requests for this plugin. Fork this project if you would like to keep it alive.

**Pull request closed without merging**
